# In this YAML file, you can configure things that affect:
#         (a) Both parts of the table;
#         (b) just Part 1 of the table - "Whether a weapon was used"; and
#         (c) just Part 2 of the Table - "What weapon was used".

BOTH_PARTS_OF_THE_TABLE:
  WEIGHT_VARIABLES:
    - [2009, C11IndivWgt]
    - [2010, C11IndivWgt]
    - [2011, C11IndivWgt]
    - [2012, C11IndivWgt]
    - [2013, C11IndivWgt]
    - [2014, C11IndivWgt]
    - [2015, C11IndivWgt]
    - [2016, C11IndivWgt]
    - [2017, C11IndivWgt]
    - [2018, C11IndivWgt]
    - [2019, C11IndivWgt]
  COL_NAMES: 
    - "Men"
    - "Women"
    - "All"
  OFFENCE_CODES:
    - ["Robbery", [41,42]]
  TITLE_OF_TABLE: "Table 7: Estimated number of robbery incidents against men and women"
  TITLES_OF_SUBTABLES:
    - "Table 7: Estimated number of robbery incidents against men and women"
  SUBTITLES:
    - "England and Wales"
    - "Personal incidents, percentages and number of incidents$$Note_2$$"
  FOOTNOTES:
    - "Includes attempted robbery."
    - "Percentages may not sum to 100 due to rounding."
PART_ONE:
  NAME: "Number of incidents (thousands)"
  ROW_LABELS:
    - [robber_i,  "Robbery$$Note_1$$"]
    - [NULL,      "Unweighted base - number of adults"]
