# In this YAML file, you can configure things that affect:
#         (a) Both parts of the table;
#         (b) just Part 1 of the table - "Whether a weapon was used"; and
#         (c) just Part 2 of the Table - "What weapon was used".

  BOTH_PARTS_OF_THE_TABLE:
    WEIGHT_VARIABLES:
      - [2009, C11IndivWgt]
      - [2010, C11IndivWgt]
      - [2011, C11IndivWgt]
      - [2012, C11IndivWgt]
      - [2013, C11IndivWgt]
      - [2014, C11IndivWgt]
      - [2015, C11IndivWgt]
      - [2016, C11IndivWgt]
      - [2017, C11IndivWgt]
      - [2018, C11IndivWgt]
      - [2019, C11IndivWgt]
    COL_NAMES: 
      - "Men"
      - "Women"
      - "All"
    OFFENCE_CODES:
      - ["All Violence", [11,12,13,21,32,33]]
    TITLE_OF_TABLE: "Table 7: Estimated number of violent incidents against men and women by violence"
    TITLES_OF_SUBTABLES:
      - "Table 7: Estimated number of violent incidents against men and women by violence"
    SUBTITLES:
      - "England and Wales"
      - "Personal incidents, percentages and numbers of incidents$$Note_2$$$$Note_3$$"
    FOOTNOTES:
      - "Owing to possible missing data regarding the relationship between the respondent (victim) and the offender for particular offences, the domestic violence/acquaintance/stranger breakdown may not sum to the total for all violence."
      - "Percentages may not sum to 100 due to rounding."
      - "'All violence' includes violence with injury and violence without injury. See Section 5.1 of the User Guide for more information."
  PART_ONE:
    NAME: "Number$$Note_2$$ of incidents (thousands)"
    ROW_LABELS:
      - [violnr_i,  "All violence$$Note_1$$$$Note_3$$"]
      - [wound_i,   "Wounding"]
      - [cominj_i,  "Assault with minor injury"]
      - [vininr_i,  "Violence without injury"]
      - [NULL, "Unweighted base - number of adults"]
