# In this YAML file, you can configure things that affect:
#         (a) Both parts of the table;
#         (b) just Part 1 of the table - "Offender under influence of alcohol"; and
#         (c) just Part 2 of the Table - "Offender under influence of drugs".

BOTH_PARTS_OF_THE_TABLE:
    WEIGHT_VARIABLES:
        - [2009, c11weighti]
        - [2010, c11weighti]
        - [2011, c11weighti]
        - [2012, c11weighti]
        - [2013, c11weighti]
        - [2014, c11weighti]
        - [2015, c11weighti]
        - [2016, c11weighti]
        - [2017, c11weighti]
        - [2018, c11weighti]
        - [2019, c11weighti]
    OFFENCE_CODES:
        - ["Robbery", [41,42]]
    TITLE_OF_TABLE: "Table 9: Proportion of incidents of robbery where the victim believed the offender(s) to be under the influence of alcohol or drugs"
    TITLES_OF_SUBTABLES:
        - "Table 9: Proportion of incidents of robbery where the victim believed the offender(s) to be under the influence of alcohol or drugs$$Note_1$$"
    SUBTITLES:
        - "England and Wales"
        - "Personal incidents, percentages"
    FOOTNOTES:
        - "Includes attempted robbery."
        - "Questions asked only if the victim was able to say something about the offender(s), and if there was more than one offender, victims were asked if any of the offenders were perceived to be under the influence. Questions were not asked if any offender(s) were perceived to be under the age of 10."
        -  master_config$SIGNIFICANCE_TESTING$FOOTNOTE
PART_ONE:
    NAME: "Offender(s) perceived to be under influence of alcohol$$Note_2$$"
    ROW_LABELS:
        - "Yes"
        - "No"
        - "Don't know"
        - "Unweighted base - number of incidents"
PART_TWO:
    NAME: "Offender(s) perceived to be under influence of drugs$$Note_2$$"
    ROW_LABELS:
        - "Yes"
        - "No"
        - "Don't know"
        - "Unweighted base - number of incidents"

