# In this YAML file, you can configure things that affect:
#         (a) Both parts of the table;
#         (b) just Part 1 of the table - "Respondent was/was-not emotionally affected"; and
#         (c) just Part 2 of the Table - "Type of emotional response experienced".

BOTH_PARTS_OF_THE_TABLE:
    WEIGHT_VARIABLES:
        - [2009, c11weighti]
        - [2010, c11weighti]
        - [2011, c11weighti]
        - [2012, c11weighti]
        - [2013, c11weighti]
        - [2014, c11weighti]
        - [2015, c11weighti]
        - [2016, c11weighti]
        - [2017, c11weighti]
        - [2018, c11weighti]
        - [2019, c11weighti]
    OFFENCE_CODES:
        - ["Theft from the person", [43,44]]
        - ["Other theft of property", [67]]
    TITLE_OF_TABLE: "Table 3: Items stolen in incidents of personal and other theft"
    TITLES_OF_SUBTABLES:
        - "Table 3a: Items stolen in incidents of theft from the person"
        - "Table 3b: Items stolen in incidents of other theft of property"
    SUBTITLES:
        - "England and Wales"
        - "Personal incidents, percentages"
    FOOTNOTES:
        - "Figures may not sum to 100 as more than one response possible."
        - "'Cheque book' was incorporated into the 'Documents' category from the year ending March 2012 onwards."
        - "'Computers/other electrical goods' includes televisions, videos, stereos, cameras, computer equipment, MP3 players, DVD players and games consoles."
        - "Separate categories for jewellery and watches were introduced in the year ending March 2015."
        -  master_config$SIGNIFICANCE_TESTING$FOOTNOTE
PART_TWO:
    NAME: "Items stolen$$Note_1$$"
    ROW_LABELS:
        - [whast_pt1, "Briefcase/bag"]
        - [whast_pt2, "Purse/wallet"]
        - [whast_pt3, "Cash/foreign currency"]
        - [whast_pt4, "Credit cards"]
        - [whast_pt5, "Mobile"]
        - [whast_pt6, "Jewellery/watches"]
        - [whast_pt7, "Clothing"]
        - [whast_pt8, "Documents$$Note_2$$"]
        - [whast_pt9, "Computers/other electrical goods$$Note_3$$"]
        - [whast_pt10, "CDs/tapes/videos/DVDs"]
        - [whast_pt11, "House keys"]
        - [whast_pt12, "Car keys"]
        - [whast_pt13, "Tools"]
        - [whast_pt14, "Other stolen items"]
        - [whast_pt15, "Food/toiletries/cigarettes"]
        - [whast_pt16, "Jewellery$$Note_4$$"]
        - [whast_pt17, "Watches$$Note_4$$"]
        - [NULL, "Unweighted base - number of incidents"]
