# In this YAML file, you can configure things that affect:
#         (a) Three parts of the table;
#         (b) just Part 1 of the Table - "Rated seriousness of incidents"; and
#         (c) just Part 2 of the Table - "Whether incident perceived as a crime"; and

BOTH_PARTS_OF_THE_TABLE:
    WEIGHT_VARIABLES:
        - [2009, c11weighti]
        - [2010, c11weighti]
        - [2011, c11weighti]
        - [2012, c11weighti]
        - [2013, c11weighti]
        - [2014, c11weighti]
        - [2015, c11weighti]
        - [2016, c11weighti]
        - [2017, c11weighti]
        - [2018, c11weighti]
        - [2019, c11weighti]
    OFFENCE_CODES:
        - ["All domestic burglary in a dwelling", [51,52,53]]
        - ["Domestic burglary in a dwelling with entry", [51,52]]
        - ["Attempted domestic burglary in a dwelling", [53]]
        - ["All domestic burglary in a non-connected building to a dwelling", [50,57,58]]
        - ["Domestic burglary in a non-connected building to a dwelling with entry", [57,58]]
        - ["Attempted domestic burglary in a non-connected building to a dwelling", [50]]
    TITLE_OF_TABLE: "Table 9: Perceived seriousness of incidents of domestic burglary"
    TITLES_OF_SUBTABLES: 
        - "Table 9a: Perceived seriousness of incidents of all domestic burglary in a dwelling"
        - "Table 9b: Perceived seriousness of incidents of domestic burglary in a dwelling with entry"
        - "Table 9c: Perceived seriousness of incidents of attempted domestic burglary in a dwelling"
        - "Table 9d: Perceived seriousness of incidents of all domestic burglary in a non-connected building to a dwelling"
        - "Table 9e: Perceived seriousness of incidents of domestic burglary in a non-connected building to a dwelling with entry"
        - "Table 9f: Perceived seriousness of incidents of attempted domestic burglary in a non-connected building to a dwelling$$Note_1$$"
    SUBTITLES:
        - "England and Wales"
        - "Household incidents, percentages"
    FOOTNOTES:
        - "For survey years ending March 2017 and year ending March 2019 to March 2020 estimates are based on fewer than 50 respondents and should be interpreted with caution."
        - "1-6 represents the least serious assessment and 14-20 represents the most serious."
        -  master_config$SIGNIFICANCE_TESTING$FOOTNOTE
PART_ONE:
    NAME: "Rated seriousness of crime$$Note_2$$"
    ROW_LABELS:
        - "1-6"
        - "7-13"
        - "14-20"
        - "Mean rating"
        - "Unweighted base - number of incidents"
PART_TWO:
    ROW_LABELS:
        - "It was a crime"
        - "It was wrong, but not a crime"
        - "It was just something that happens"
        - "Unweighted base - number of incidents"
