# In this YAML file, you can configure things that affect:
#         (a) Three parts of the table;
#         (b) just Part 1 of the Table - "Rated seriousness of incidents"; and
#         (c) just Part 2 of the Table - "Whether incident perceived as a crime"; and

BOTH_PARTS_OF_THE_TABLE:
    WEIGHT_VARIABLES:
        - [2009, c11weighti]
        - [2010, c11weighti]
        - [2011, c11weighti]
        - [2012, c11weighti]
        - [2013, c11weighti]
        - [2014, c11weighti]
        - [2015, c11weighti]
        - [2016, c11weighti]
        - [2017, c11weighti]
        - [2018, c11weighti]
        - [2019, c11weighti]
    OFFENCE_CODES:
        - ["All vehicle-related theft", [60,61,62,63,71,72]]
        - ["Theft of vehicle", [60,62]]
        - ["Theft from vehicle", [61,63]]
        - ["Attempted theft of and from vehicle", [71,72]]
    TITLE_OF_TABLE: "Table 9: Perceived seriousness of incidents of vehicle-related theft"
    TITLES_OF_SUBTABLES:
        - "Table 9a: Perceived seriousness of incidents of all vehicle-related theft"
        - "Table 9b: Perceived seriousness of incidents of theft of vehicles"
        - "Table 9c: Perceived seriousness of incidents of theft from vehicles"
        - "Table 9d: Perceived seriousness of incidents of attempted theft of and from vehicles"
    SUBTITLES:
        - "England and Wales"
        - "Household incidents, percentages"
    FOOTNOTES:
        - "1-6 represents the least serious assessment and 14-20 represents the most serious."
        -  master_config$SIGNIFICANCE_TESTING$FOOTNOTE
PART_ONE:
    NAME: "Rated seriousness of crime$$Note_1$$"
    ROW_LABELS:
        - "1-6"
        - "7-13"
        - "14-20"
        - "Mean rating"
        - "Unweighted base - number of incidents"
PART_TWO:
    ROW_LABELS:
        - "It was a crime"
        - "It was wrong, but not a crime"
        - "It was just something that happens"
        - "Unweighted base - number of incidents"
