# In this YAML file, you can configure things that affect:
#         (a) Both parts of the table;
#         (b) just Part 1 of the table - "Proportion of all incidents"; and
#         (c) just Part 2 of the Table - "Number of incidents".

BOTH_PARTS_OF_THE_TABLE:
    WEIGHT_VARIABLES:
        - [2009, c11weighti]
        - [2010, c11weighti]
        - [2011, c11weighti]
        - [2012, c11weighti]
        - [2013, c11weighti]
        - [2014, c11weighti]
        - [2015, c11weighti]
        - [2016, c11weighti]
        - [2017, c11weighti]
        - [2018, c11weighti]
        - [2019, c11weighti]
    OFFENCE_CODES:
        - ["All violence$$Note_1$$", [11,12,13,21,32,33]]
    TITLE_OF_TABLE: "Table 11: Violent incidents where the victim believed the offender(s) to be under the influence of alcohol or drugs$$Note_2$$"
    TITLES_OF_SUBTABLES:
        - "Table 11: Violent incidents where the victim believed the offender(s) to be under the influence of alcohol or drugs$$Note_2$$"
    SUBTITLES:
        - "England and Wales"
        - "Personal incidents, percentages and numbers of incidents"
    FOOTNOTES:
        - "All violence' includes violence with injury and violence without injury. See Section 5.1 of the User Guide for more information."
        - "Questions asked only if the victim was able to say something about the offender(s), and if there was more than one offender, victims were asked if any of the offenders were perceived to be under the influence. Questions were not asked if any offender(s) were perceived to be under the age of 10."
        - "Unweighted base refers to those asked the question about whether they perceived the offender to be under the influence of alcohol; base size for offender(s) perceived to be under the influence of drugs will be similar."
        -  master_config$SIGNIFICANCE_TESTING$FOOTNOTE
PART_ONE:
    NAME: "Proportion of all violent incidents$$Note_1$$"
    ROW_LABELS:
        - "Under the influence of alcohol$$Note_2$$"
        - "Under the influence of drugs$$Note_2$$"
        - "Unweighted base - number of incidents$$Note_3$$"
PART_TWO:
    NAME: "Number of violent incidents (thousands)"
    ROW_LABELS:
        - "Under the influence of alcohol$$Note_2$$"
        - "Under the influence of drugs$$Note_2$$"
        - "Unweighted base - number of incidents$$Note_3$$"
