# In this YAML file, you can configure things that affect:
#         (a) Both parts of the table;
#         (b) just Part 1 of the table - "Respondent was/was-not emotionally affected"; and
#         (c) just Part 2 of the Table - "Type of emotional response experienced".

ALL_PARTS:
    WEIGHT_VARIABLES:
        - [2009, c11weighti]
        - [2010, c11weighti]
        - [2011, c11weighti]
        - [2012, c11weighti]
        - [2013, c11weighti]
        - [2014, c11weighti]
        - [2015, c11weighti]
        - [2016, c11weighti]
        - [2017, c11weighti]
        - [2018, c11weighti]
        - [2019, c11weighti]
    OFFENCE_CODES:
        - ["All violence", [11,12,13,21,32,33]]
        - ["Violence with injury", [11,12,13,21,32,33]]
        - ["Wounding", [11,12,13,21,32,33]]
        - ["Assault with minor injury", [11,12,13,21,32,33]]
        - ["Violence without injury", [11,12,13,21,32,33]]
        - ["Domestic violence", [11,12,13,21,32,33]]
        - ["Violence by an acquaintance", [11,12,13,21,32,33]]
        - ["Violence by a stranger", [11,12,13,21,32,33]]
    TITLE_OF_TABLE: "Table 5: Emotional impact of incidents of violence"
    TITLES_OF_SUBTABLES:
        - "Table 5a: Emotional impact of incidents of all violence$$Note_3$$"
        - "Table 5b: Emotional impact of incidents of violence with injury$$Note_4$$"
        - "Table 5c: Emotional impact of incidents of wounding"
        - "Table 5d: Emotional impact of incidents of assault with minor injury"
        - "Table 5e: Emotional impact of incidents of violence without injury"
        - "Table 5f: Emotional impact of incidents of domestic violence$$Note_5$$"
        - "Table 5g: Emotional impact of incidents of violence by an acquaintance$$Note_6$$"
        - "Table 5h: Emotional impact of incidents of violence by a stranger$$Note_7$$"
    SUBTITLES:
        - "England and Wales"
        - "Personal incidents, percentages"
    FOOTNOTES:
        - "Figures here are based on incidents in which the victim reported that they were emotionally affected by the incident."
        - "Figures may not sum to 100 as more than one response is possible."
        - "'All violence' includes violence with injury and violence without injury. See Section 5.1 of the User Guide for more information."
        - "'Violence with injury' includes wounding and assault with minor injury."
        - "Domestic violence comprises violence that involves partners, ex-partners, other relatives or household members. See Section 5.1 of the User Guide for more information."
        - "Acquaintance violence comprises violence in which the victim knew one or more of the offenders, at least by sight, but it excludes domestic violence. See Section 5.1 of the User Guide for more information."
        - "Stranger violence comprises violence in which the victim did not have any information about the offender(s) or did not know and had never seen the offender(s) before. See Section 5.1 of the User Guide for more information."
        -  master_config$SIGNIFICANCE_TESTING$FOOTNOTE
PART_ONE:
    NAME: "Was the respondent emotionally affected?"
    ROW_LABELS:
        - "Respondent was emotionally affected"
        - "Respondent was not emotionally affected"
        - "Unweighted base - number of incidents"
PART_TWO:
    NAME: "Extent of impact"
    ROW_LABELS:
        - "Very much"
        - "Quite a lot"
        - "Just a little"
        - "Unweighted base - number of incidents"
PART_THREE:
    NAME: "Type of emotional response experienced$$Note_1$$$$Note_2$$"
    ROW_LABELS:
        - [anger, "Anger"]
        - [shock, "Shock"]
        - [fear, "Fear"]
        - [sleeping, "Difficulty sleeping"]
        - [crying, "Crying/tears"]
        - [depress, "Depression"]
        - [anxiety, "Anxiety or panic attacks"]
        - [confid, "Loss of confidence or feeling vulnerable"]
        - [annoy, "Annoyance"]
        - [othemot, "Other"]
        - [NULL, "Unweighted base - number of incidents"]
