WEIGHT_VARIABLES:
    - [2009, c11weighti]
    - [2010, c11weighti]
    - [2011, c11weighti]
    - [2012, c11weighti]
    - [2013, c11weighti]
    - [2014, c11weighti]
    - [2015, c11weighti]
    - [2016, c11weighti]
    - [2017, c11weighti]
    - [2018, c11weighti]
    - [2019, c11weighti]
OFFENCE_CODES:
    - ["All criminal damage", [80,81,82,83,84,85,86]]    
    - ["Criminal damage to a vehicle", [81,82]]
    - ["Arson and other criminal damage", [80,83,84,85,86]]
TITLE_OF_TABLE: "Table 4: Cost of damage in incidents of criminal damage"
TITLES_OF_SUBTABLES:
    - "Table 5a: Cost of damage in incidents of all criminal damage"
    - "Table 5b: Cost of damage in incidents of criminal damage to a vehicle"
    - "Table 5c: Cost of damage in incidents of arson and other criminal damage"
SUBTITLES:
    - "England and Wales"
    - "Household incidents, percentages"
FOOTNOTES:
    - "Respondents were asked to estimate the total cost of damage caused. The mean is affected by the small number of offences with high costs and the median is affected by the high number of offences with no cost, hence both are presented together."
    - "Values include all respondents who said damage to property was caused, even if damage was valued at zero."
    - "It is not possible to calculate statistical significance for the median cost."
    -  master_config$SIGNIFICANCE_TESTING$FOOTNOTE
ROW_LABELS:
    - "No cost"
    - "£1 to £19"
    - "£20 to £49"
    - "£50 to £99"
    - "£100 to £199" 
    - "£200 to £499"
    - "£500 to £999"
    - "£1,000 or more"
    - "Mean cost$$Note_1$$"
    - "Median cost$$Note_1$$$$Note_2$$$$Note_3$$"
    - "Unweighted base - number of incidents"
GROUPED_TOTAL_DAMAGE_VARIABLE: totdam2
