# In this YAML file, you can configure things that affect:
#         (a) Both parts of the table;
#         (b) just Part 1 of the table - "Whether they saw offenders"; and
#         (c) just Part 2 of the Table - "Of those who were at home, aware and saw offender(s)".

BOTH_PARTS_OF_THE_TABLE:
    WEIGHT_VARIABLES:
        - [2009, c11weighti]
        - [2010, c11weighti]
        - [2011, c11weighti]
        - [2012, c11weighti]
        - [2013, c11weighti]
        - [2014, c11weighti]
        - [2015, c11weighti]
        - [2016, c11weighti]
        - [2017, c11weighti]
        - [2018, c11weighti]
        - [2019, c11weighti]
    OFFENCE_CODES:
        - ["All domestic burglary in a dwelling", [51,52,53]]
        - ["Domestic burglary in a dwelling with entry", [51,52]]
        - ["Attempted domestic burglary in a dwelling", [53]]
        - ["All domestic burglary in a non-connected building to a dwelling", [50,57,58]]
        - ["Domestic burglary in a non-connected building to a dwelling with entry", [57,58]]
        - ["Attempted domestic burglary in a non-connected building to a dwelling", [50]]
    TITLE_OF_TABLE: "Table 10: Contact with offenders in incidents of domestic burglary"
    TITLES_OF_SUBTABLES:
        - "Table 10a: Contact with offenders in incidents of domestic burglary in a dwelling"
        - "Table 10b: Contact with offenders in incidents of domestic burglary in a dwelling with entry"
        - "Table 10c: Contact with offenders in incidents of attempted domestic burglary in a dwelling"
        - "Table 10d: Contact with offenders in incidents of domestic burglary in a non-connected building to a dwelling"
        - "Table 10e: Contact with offenders in incidents of domestic burglary in a non-connected building to a dwelling with entry"
        - "Table 10f: Contact with offenders in incidents of attempted domestic burglary in a non-connected building to a dwelling$$Note_1$$"
    SUBTITLES:
        - "England and Wales"
        - "Household incidents, percentages"
    FOOTNOTES:
        - "For survey years ending March 2016,  March 2017,  March 2019 and March 2020, estimates based on fewer than 50 respondents should be interpreted with caution. This is indicated by a '†'."
        - "Incidents involving threat or use of force or threats."
        - "Unweighted base is where someone was at home and aware and did see offender(s)."
        - master_config$SIGNIFICANCE_TESTING$FOOTNOTE
PART_ONE:
    NAME: " "
    ROW_LABELS: 
        - [somehome, "Someone at home"]
        - [notaware, "      At home and unaware"]
        - [yesaware, "      At home and aware but did not see offender(s)"]
        - [yessawoff,"      At home and aware and did see offender(s)"]
        - [noaware,  "No one at home"]
        - [NULL, "Unweighted bases - number of incidents"]
PART_TWO:
    NAME: "Of those who were at home, aware and saw offender(s):"
    ROW_LABELS:
        - [yesviofor, "Force or violence threatened or used$$Note_2$$"]
        - [yesthreat, "     Force or violence threatened"]
        - [nothreat, "     No Force or violence threatened"]
        - [yesuse,    "     Force or violence used"]
        - [nouse,    "     No Force or violence used"]
        - [noviofor,  "Neither threats nor use of force or violence"]
        - [NULL, "Unweighted base - number of incidents$$Note_3$$"]
