WEIGHT_VARIABLES:
    - [2009, c11weighti]
    - [2010, c11weighti]
    - [2011, c11weighti]
    - [2012, c11weighti]
    - [2013, c11weighti]
    - [2014, c11weighti]
    - [2015, c11weighti]
    - [2016, c11weighti]
    - [2017, c11weighti]
    - [2018, c11weighti]
    - [2019, c11weighti]
OFFENCE_CODES:
    - ["All other household theft", [55,56,65]]
    - ["Theft from a dwelling", [55, 56]]
    - ["Theft from outside a dwelling", [65]]
TITLE_OF_TABLE: "Table XX cost of stolen items in bicycle theft incidents"
TITLES_OF_SUBTABLES:
    - "Table 3a: Cost of stolen items in incidents of all other household theft"
    - "Table 3b: Cost of stolen items in incidents of theft from a dwelling"
    - "Table 3b: Cost of stolen items in incidents of theft from outside a dwelling"
SUBTITLES:
    - "England and Wales"
    - "Household incidents, percentages"
FOOTNOTES:
    - "No cost includes respondents who said no item(s) were stolen."
    - "Respondents were asked to estimate the total cost of items stolen. The mean is affected by the small number of offences with high costs, hence the median (or middle value in the range) is also presented."
    - "Values include all respondents who said one or more items were stolen, even if the cost was valued at zero."
    - "It is not possible to calculate statistical significance for the median cost."
    -  master_config$SIGNIFICANCE_TESTING$FOOTNOTE
ROW_LABELS:
    - "No cost$$Note_1$$"
    - "£1 to £19"
    - "£20 to £49"
    - "£50 to £99"
    - "£100 to £199"
    - "£200 to £499"
    - "£500 to £999"
    - "£1000 or more"
    - "Mean cost$$Note_2$$"
    - "Median cost$$Note_2$$$$Note_3$$$$Note_4$$"
    - "Unweighted base - number of incidents"
